name: Build APK
on:
  workflow_dispatch:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Unpack
        run: unzip -q "$(ls *v2*.zip | head -n1)"
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      - uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.5'
      - name: Build
        working-directory: lsposed_module
        run: gradle assembleDebug --stacktrace
      - uses: actions/upload-artifact@v4
        with:
          name: wcsspoof-debug-apk
          path: lsposed_module/app/build/outputs/apk/debug/*.apk
